### ISSUE TITLE
Decidir que quereis hacer cada uno

### ISSUE THREAD

**Issue by DanielAlba96** [Arquisoft/participationSystem1a#5]

**Comment by DanielAlba96** [comment]
Tareas:
- Manejo de errores: Pagina html y redirección del controlador
- Lista de tareas con enlaces para apoyarlas en index.html ordenadas por popularidad
- Sistema de creación de propuestas (con sus categorias)
- Sistema de configuración (y borrado de propuestas)
- Control de Acceso a recursos (solo admin puede acceder a config.html)
- Sistema de votación de comentarios
- Sistema de apoyo de propuestas
- Envió de los logs con Kafka
- KafkaConsumer para recibir nuestros propios logs
- Caso de uso con cucumber

Si tenéis que tocar algo del modelo avisar primero

**Comment by DanielAlba96** [comment]
Voy a hacer

- [x] Lista de tareas con enlaces para apoyarlas en index.html ordenadas por popularidad
- [x] Sistema de apoyo de propuestas
- [x] Manejo de errores: Pagina html y redirección del controlador

**Comment by duque96** [comment]
Voy a hacer

- [x]  Sistema de votacion de los comentarios

- [x] Sistema de creacion de propuestas (con sus categorias)

- [x] Control de acceso a recursos (solo admin puede acceder a config.html)

**Comment by rdlvarga** [comment]
- Envío de logs con kafka

- KafkaConsumer para recibir nuestros propios logs

**Comment by IgnacioEscribano** [comment]
- Sistema de configuración

- Caso de uso con cucumber

**Comment by DanielAlba96** [comment]
FINISHED
